-- DDL generated by Postico 1.5.21
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE option_prices (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    contract text UNIQUE,
    underlying_ticker text,
    strike_price integer,
    expiration_date date,
    ask_price double precision,
    ask_time timestamp without time zone,
    ask_size integer,
    bid_price double precision,
    bid_time timestamp without time zone,
    bid_size integer,
    last_price double precision,
    last_time timestamp without time zone,
    last_size integer,
    implied_volatility double precision,
    delta double precision,
    gamma double precision,
    theta double precision,
    vega double precision,
    put_call put_call,
    ask_implied_volatility double precision,
    bid_implied_volatility double precision,
    underlying_price double precision
);


CREATE UNIQUE INDEX option_prices_pkey ON option_prices(id int8_ops);
CREATE INDEX option_prices_contract_idx ON option_prices(contract text_ops);
CREATE INDEX option_prices_underlying_ticker_expiration_date_idx ON option_prices(underlying_ticker text_ops,expiration_date date_ops);
CREATE UNIQUE INDEX option_prices_contract_key ON option_prices(contract text_ops);

-- DDL generated by Postico 1.5.21
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE subscriptions (
    symbol text PRIMARY KEY
);

CREATE UNIQUE INDEX subscriptions_pkey ON subscriptions(symbol text_ops);
